net_sched: Make qcb as __maybe_unused
To work around a Clang bug, WireGuard turns BUILD_BUG_ON into a no-op.
As a result, Clang warns that qcb is unused:

../include/net/sch_generic.h:251:23: error: unused variable 'qcb'
[-Werror,-Wunused-variable]
        struct qdisc_skb_cb *qcb;
                             ^
1 error generated.

Mark qcb as __maybe_unused so that Clang no longer warns.

Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
(cherry picked from commit 24ad9b19a1e7380347c97ffacaf8be8f76c78374)
(cherry picked from commit 7ecba930b88adeb7abd4099160a9400cdb99aa8d)
(cherry picked from commit 0dcaa99011288a8484d8933aaf00faabd09d7cbf)
(cherry picked from commit 53ea1dee1c8b0faf57da21c18146ea3e3dcea7ee)
(cherry picked from commit 65672c8613be01a80c6ccb254e12998443d63c27)
(cherry picked from commit 1c4d0a57323aa136b76ad468b3ea70c5da3e62ee)
(cherry picked from commit fff50871bde50236813a94cfcaff99bd69b87efe)
(cherry picked from commit 099e616632ba37a08d4a6ae05aff60d3a2b0dbf8)
(cherry picked from commit 77bd7f05cd9ac692e41ca1b7bf030559cf96b51f)